{% set name = "taskgraph" %}
{% set version = "0.11.1" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 536cf4fc4dde6ae9f953363b52917f3eb961313178053694a154d872b5f3fc3d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - psutil
    - retrying >=1.3.0
    - setuptools

test:
  requires:
    - pytest
    - rstcheck
    - python {{ python_min }}
  source_files:
    - tests
    - HISTORY.rst
  imports:
    - taskgraph
  commands:
    - pytest tests

about:
  home: https://github.com/natcap/taskgraph
  license_file: LICENSE.txt
  license: BSD-3-Clause
  license_family: BSD
  summary: Task-based parallelism and avoided recomputation for Python
  dev_url: https://github.com/natcap/taskgraph

extra:
  recipe-maintainers:
    - dcdenu4
    - phargogh
